---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: helloworld
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./helloworld
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-samples
  targetNamespace: feng-flux

